-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v1.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer

-   repo: https://github.com/Lucas-C/pre-commit-hooks
    sha: v1.1.5
    hooks:
    -   id: remove-crlf
    -   id: forbid-tabs

-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      python_version: python3.6
