FROM arm32v6/python:3.6-alpine3.6

RUN apk --no-cache add tzdata git curl

COPY . /app
WORKDIR /app

RUN curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python

RUN $HOME/.poetry/bin/poetry build
RUN pip install --upgrade pip
RUN pip install --no-cache-dir --find-links=/app/dist wartracker

ENV PYTHONPATH /app
CMD ["wartracker"]
